main: org.light.source.DeathMatch
name: DeathMatch
version: ${project.version}
depend: [CrackShot, Vault]
commands:
  데스매치:
    description: Related with DeathMatch
  참여:
    aliases: [join]
    description: Join Command
  나가기:
    aliases: [leave]
    description: Leave Command
  랭크:
    aliases: [rank]
    description: Rank
  킬뎃:
    aliases: [kd]
    description: K/D
  hd:
    description: hologram
  dayz:
    description: about dayz
